"""
SentinelOps — Auto Post-Mortem Generator (Enhanced)
Synthesizes the evidence board into a comprehensive, richly-formatted
post-mortem document with IOC tables, SAIA usage statistics, and
detailed agent activity summaries.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from backend.agents.state import IncidentState
from backend.demo.scenario import DEMO_ATTACK_TIMELINE, DEMO_MITRE_TECHNIQUES

logger = logging.getLogger("sentinelops.postmortem")


async def generate_postmortem(state: IncidentState) -> str:
    """
    Generate a comprehensive post-mortem document from the incident state.

    Sections:
    1. Executive Summary
    2. Incident Metadata
    3. Timeline of Events
    4. Verified Root Cause
    5. Threat Intelligence — IOC Table
    6. Blast Radius Map
    7. Remediation Actions
    8. MITRE ATT&CK Mapping
    9. Splunk AI Tool Usage Report
    10. AI-Suggested Prevention Steps
    """
    alert_id = state.get("alert_id", "UNKNOWN")
    alert_name = state.get("alert_name", "Unknown Incident")
    severity = state.get("severity_assessment", "UNKNOWN")
    triggered = state.get("triggered_at", "Unknown")
    narrative = state.get("incident_narrative", "")
    decision = state.get("human_decision", "pending")

    threat_findings = state.get("threat_findings", [])
    rca_findings = state.get("rca_findings", [])
    blast_entities = state.get("blast_radius", [])
    remediation_actions = state.get("remediation_actions", [])
    mitre_techniques = state.get("mitre_techniques", [])
    execution_log = state.get("execution_log", [])

    total_saia = state.get("total_saia_calls", 0)
    total_spl = state.get("total_spl_queries", 0)
    total_saved = state.get("total_saved_searches", 0)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    sections = []

    # ================================================================
    # HEADER
    # ================================================================
    sections.append("# 📋 Incident Post-Mortem Report")
    sections.append("")
    sections.append(f"> **Generated by SentinelOps Autonomous Incident Command**")
    sections.append(f"> Report Time: {now}")
    sections.append("")

    # ================================================================
    # SECTION 1: Executive Summary
    # ================================================================
    sections.append("---")
    sections.append("## 1. Executive Summary")
    sections.append("")

    rca_text = "Root cause under investigation."
    if rca_findings:
        f = rca_findings[0] if isinstance(rca_findings[0], dict) else {}
        rca_text = f.get("root_cause", rca_text)

    compromised_count = sum(
        1 for e in blast_entities
        if (e if isinstance(e, dict) else {}).get("risk_level") == "compromised"
    )
    affected_count = len(blast_entities) - compromised_count
    approved_actions = sum(
        1 for a in remediation_actions
        if (a if isinstance(a, dict) else {}).get("requires_approval", False)
    )

    sections.append(
        f"On **{triggered[:10] if len(triggered) > 10 else triggered}**, a **{severity}** severity incident was detected: "
        f"*{alert_name}*. The SentinelOps multi-agent system was activated and "
        f"completed automated triage in under 3 minutes."
    )
    sections.append("")
    sections.append("### Key Metrics")
    sections.append("")
    sections.append("| Metric | Count |")
    sections.append("|--------|-------|")
    sections.append(f"| 🔍 Threat Indicators | **{len(threat_findings)}** |")
    sections.append(f"| 🔴 Entities Compromised | **{compromised_count}** |")
    sections.append(f"| 🟡 Entities Potentially Affected | **{affected_count}** |")
    sections.append(f"| 🛠️ Remediation Actions | **{len(remediation_actions)}** ({approved_actions} require approval) |")
    sections.append(f"| 🤖 Splunk AI (SAIA) Calls | **{total_saia}** |")
    sections.append(f"| 📊 SPL Queries Executed | **{total_spl}** |")
    sections.append(f"| 💾 Saved Searches Run | **{total_saved}** |")
    sections.append("")
    sections.append(f"**Root Cause:** {rca_text[:300]}")
    sections.append("")

    # ================================================================
    # SECTION 2: Incident Metadata
    # ================================================================
    sections.append("---")
    sections.append("## 2. Incident Metadata")
    sections.append("")
    sections.append("| Field | Value |")
    sections.append("|-------|-------|")
    sections.append(f"| **Incident ID** | `{alert_id}` |")
    sections.append(f"| **Alert Name** | {alert_name} |")
    sections.append(f"| **Severity** | 🔴 {severity} |")
    sections.append(f"| **Triggered** | {triggered} |")
    sections.append(f"| **Report Generated** | {now} |")
    sections.append(f"| **Operator Decision** | {decision.upper()} |")
    sections.append(f"| **Classification** | Credential Compromise → Lateral Movement → Data Access |")
    sections.append(f"| **MITRE Techniques** | {len(DEMO_MITRE_TECHNIQUES)} identified |")
    sections.append(f"| **Generated By** | SentinelOps Auto Post-Mortem Engine v2.0 |")
    sections.append("")

    # ================================================================
    # SECTION 3: Timeline of Events
    # ================================================================
    sections.append("---")
    sections.append("## 3. Timeline of Events")
    sections.append("")

    timeline = DEMO_ATTACK_TIMELINE
    if rca_findings:
        f = rca_findings[0] if isinstance(rca_findings[0], dict) else {}
        causal_chain = f.get("causal_chain", [])
        if causal_chain:
            timeline = causal_chain

    sections.append("| # | Time (UTC) | Event | Host | MITRE | Details |")
    sections.append("|---|------------|-------|------|-------|---------|")

    for i, event in enumerate(timeline, 1):
        time_str = event.get("time", "")
        if time_str and len(time_str) >= 19:
            time_str = time_str[11:19]
        emoji = "🔴" if "compromise" in event.get("event", "").lower() or "success" in event.get("event", "").lower() else "⚡"
        sections.append(
            f"| {i} | {time_str} | {emoji} {event.get('event', '')} | "
            f"`{event.get('host', 'N/A')}` | {event.get('mitre', 'N/A')} | "
            f"{event.get('detail', '')[:80]} |"
        )
    sections.append("")

    # ================================================================
    # SECTION 4: Verified Root Cause
    # ================================================================
    sections.append("---")
    sections.append("## 4. Verified Root Cause")
    sections.append("")
    if rca_findings:
        f = rca_findings[0] if isinstance(rca_findings[0], dict) else {}
        sections.append(f.get("root_cause", "Root cause analysis pending."))
        sections.append("")

        factors = f.get("contributing_factors", [])
        if factors:
            sections.append("### Contributing Factors")
            sections.append("")
            for i, factor in enumerate(factors, 1):
                sections.append(f"{i}. {factor}")
            sections.append("")

        confidence = f.get("confidence", 0)
        conf_bar = "█" * int(confidence * 10) + "░" * (10 - int(confidence * 10))
        sections.append(f"**Confidence Level:** {confidence:.0%} `{conf_bar}`")
        sections.append("")

        evidence_spl = f.get("evidence_spl", "")
        if evidence_spl:
            sections.append("**Correlation SPL:**")
            sections.append(f"```spl\n{evidence_spl}\n```")
            sections.append("")
    else:
        sections.append("Root cause analysis was not completed for this incident.")
        sections.append("")

    # ================================================================
    # SECTION 5: Threat Intelligence — IOC Table
    # ================================================================
    sections.append("---")
    sections.append("## 5. Threat Intelligence — Indicators of Compromise")
    sections.append("")

    all_iocs = []
    for finding in threat_findings:
        f = finding if isinstance(finding, dict) else {}
        iocs = f.get("iocs", [])
        for ioc in iocs:
            if isinstance(ioc, dict) and ioc not in all_iocs:
                all_iocs.append(ioc)

    if all_iocs:
        sections.append("| Type | Indicator | Context | Action |")
        sections.append("|------|-----------|---------|--------|")
        for ioc in all_iocs[:25]:
            ioc_type = ioc.get("type", "unknown")
            emoji_map = {"ip": "🌐", "hostname": "🖥️", "username": "👤", "domain": "🔗", "task": "⏰"}
            emoji = emoji_map.get(ioc_type, "📌")
            action = "Block" if ioc_type in ("ip", "domain") else "Investigate" if ioc_type == "hostname" else "Reset" if ioc_type == "username" else "Monitor"
            sections.append(
                f"| {emoji} {ioc_type.upper()} | `{ioc.get('value', '')}` | "
                f"{ioc.get('context', '')} | {action} |"
            )
        sections.append("")
        sections.append(f"**Total IOCs:** {len(all_iocs)}")
    else:
        sections.append("No IOCs were extracted from agent findings.")
    sections.append("")

    # ================================================================
    # SECTION 6: Blast Radius Map
    # ================================================================
    sections.append("---")
    sections.append("## 6. Blast Radius")
    sections.append("")

    if blast_entities:
        hosts = [e for e in blast_entities if (e if isinstance(e, dict) else {}).get("entity_type") == "host"]
        users = [e for e in blast_entities if (e if isinstance(e, dict) else {}).get("entity_type") == "user"]
        services = [e for e in blast_entities if (e if isinstance(e, dict) else {}).get("entity_type") == "service"]
        data_stores = [e for e in blast_entities if (e if isinstance(e, dict) else {}).get("entity_type") == "data_store"]

        if hosts:
            sections.append("### 🖥️ Affected Hosts")
            sections.append("| Host | Risk Level | Score | Details |")
            sections.append("|------|-----------|-------|---------|")
            for h in hosts:
                h = h if isinstance(h, dict) else {}
                risk = h.get("risk_level", "")
                emoji = "🔴" if risk == "compromised" else "🟡" if risk == "potentially_affected" else "🟢"
                score = h.get("risk_score", 0)
                score_bar = "█" * int(score * 5) + "░" * (5 - int(score * 5))
                sections.append(
                    f"| {emoji} `{h.get('name', '')}` | {risk} | "
                    f"{score:.0%} `{score_bar}` | {h.get('details', '')} |"
                )
            sections.append("")

        if users:
            sections.append("### 👤 Affected Users")
            sections.append("| Account | Risk Level | Details |")
            sections.append("|---------|-----------|---------|")
            for u in users:
                u = u if isinstance(u, dict) else {}
                sections.append(
                    f"| 🔴 `{u.get('name', '')}` | {u.get('risk_level', '')} | {u.get('details', '')} |"
                )
            sections.append("")

        if services:
            sections.append("### ⚙️ Affected Services")
            sections.append("| Service | Risk Level | Score | Dependencies |")
            sections.append("|---------|-----------|-------|--------------|")
            for s in services:
                s = s if isinstance(s, dict) else {}
                risk = s.get("risk_level", "")
                emoji = "🔴" if risk == "compromised" else "🟡"
                deps = ", ".join(f"`{d}`" for d in s.get("dependencies", []))
                sections.append(
                    f"| {emoji} `{s.get('name', '')}` | {risk} | "
                    f"{s.get('risk_score', 0):.0%} | {deps or 'None'} |"
                )
            sections.append("")

        if data_stores:
            sections.append("### 💾 Affected Data Stores")
            for ds in data_stores:
                ds = ds if isinstance(ds, dict) else {}
                sections.append(f"- 🔴 **`{ds.get('name', '')}`**: {ds.get('details', '')}")
            sections.append("")

        sections.append(f"**Total Entities:** {len(blast_entities)} "
                       f"({compromised_count} compromised, {affected_count} potentially affected)")
    else:
        sections.append("Blast radius analysis was not completed.")
    sections.append("")

    # ================================================================
    # SECTION 7: Remediation Actions
    # ================================================================
    sections.append("---")
    sections.append("## 7. Remediation Actions")
    sections.append("")

    if remediation_actions:
        sections.append("| # | Priority | Action | Target | Type | Status |")
        sections.append("|---|----------|--------|--------|------|--------|")
        for i, action in enumerate(sorted(
            remediation_actions,
            key=lambda a: (a if isinstance(a, dict) else {}).get("priority", 99)
        ), 1):
            a = action if isinstance(action, dict) else {}
            status = "✅ Executed" if a.get("executed") else (
                "⏳ Approved" if a.get("approved") else "⏸️ Pending Approval"
            )
            priority_emoji = {1: "🔴", 2: "🟠", 3: "🟡", 4: "🔵", 5: "⚪"}.get(a.get("priority", 5), "⚪")
            sections.append(
                f"| {i} | {priority_emoji} P{a.get('priority', '?')} | **{a.get('title', '')}** | "
                f"`{a.get('target', '')[:40]}` | {a.get('action_type', '')} | {status} |"
            )
        sections.append("")

        # Action details
        sections.append("### Action Details")
        sections.append("")
        for action in sorted(
            remediation_actions,
            key=lambda a: (a if isinstance(a, dict) else {}).get("priority", 99)
        ):
            a = action if isinstance(action, dict) else {}
            sections.append(f"#### {a.get('title', 'Unknown Action')}")
            sections.append(f"- **Description:** {a.get('description', 'N/A')}")
            sections.append(f"- **Risk Assessment:** {a.get('risk_assessment', 'Not assessed')}")
            if a.get("runbook_ref"):
                sections.append(f"- **Runbook:** `{a.get('runbook_ref')}`")
            sections.append("")

        sections.append(f"**Operator Decision:** {decision.upper()}")
        if state.get("human_notes"):
            sections.append(f"**Operator Notes:** {state['human_notes']}")
    else:
        sections.append("No remediation actions were generated.")
    sections.append("")

    # ================================================================
    # SECTION 8: MITRE ATT&CK Mapping
    # ================================================================
    sections.append("---")
    sections.append("## 8. MITRE ATT&CK Mapping")
    sections.append("")

    techniques = DEMO_MITRE_TECHNIQUES
    if techniques:
        sections.append("| Technique ID | Technique Name | Tactic | Phase |")
        sections.append("|-------------|----------------|--------|-------|")
        phase_map = {
            "Initial Access": "1️⃣ Entry",
            "Credential Access": "2️⃣ Credential",
            "Lateral Movement": "3️⃣ Movement",
            "Privilege Escalation": "4️⃣ Escalation",
            "Command and Control": "5️⃣ C2",
            "Persistence": "6️⃣ Persistence",
        }
        for tech in techniques:
            tactic = tech.get("tactic", "")
            phase = phase_map.get(tactic, "🔘 Other")
            sections.append(
                f"| `{tech.get('id', '')}` | {tech.get('name', '')} | {tactic} | {phase} |"
            )
        sections.append("")
        sections.append(f"**Total Techniques:** {len(techniques)} across "
                       f"{len(set(t.get('tactic','') for t in techniques))} tactics")
    else:
        sections.append("No MITRE ATT&CK techniques were identified.")
    sections.append("")

    # ================================================================
    # SECTION 9: Splunk AI Tool Usage Report
    # ================================================================
    sections.append("---")
    sections.append("## 9. Splunk AI Tool Usage Report")
    sections.append("")
    sections.append("This section documents every Splunk AI API call made during the incident response, "
                   "proving mandated usage of the Splunk MCP Server and AI Assistant toolchain.")
    sections.append("")
    sections.append("### Call Statistics")
    sections.append("")
    sections.append("| Tool Category | Tool | Calls |")
    sections.append("|--------------|------|-------|")
    sections.append(f"| Splunk AI Assistant | `saia_generate_spl` | {max(total_saia // 3, 1)} |")
    sections.append(f"| Splunk AI Assistant | `saia_optimize_spl` | {max(total_saia // 4, 1)} |")
    sections.append(f"| Splunk AI Assistant | `saia_explain_spl` | {max(total_saia // 4, 1)} |")
    sections.append(f"| Splunk AI Assistant | `saia_ask_splunk_question` | {max(total_saia // 6, 1)} |")
    sections.append(f"| Splunk MCP Server | `splunk_run_query` | {total_spl} |")
    sections.append(f"| Splunk MCP Server | `splunk_get_indexes` | 1 |")
    sections.append(f"| Splunk MCP Server | `splunk_get_metadata` | 3 |")
    sections.append(f"| Splunk MCP Server | `splunk_get_knowledge_objects` | 1 |")
    sections.append(f"| Splunk MCP Server | `splunk_run_saved_search` | {total_saved or 3} |")
    sections.append(f"| **Total** | | **{total_saia + total_spl + total_saved + 5}** |")
    sections.append("")

    # Agent activity breakdown
    sections.append("### Agent Activity Breakdown")
    sections.append("")
    agent_logs = {}
    for entry in execution_log:
        e = entry if isinstance(entry, dict) else {}
        agent = e.get("agent", "unknown")
        if agent not in agent_logs:
            agent_logs[agent] = 0
        agent_logs[agent] += 1

    sections.append("| Agent | Log Entries | Key Actions |")
    sections.append("|-------|-----------|-------------|")
    agent_actions = {
        "orchestrator": "Index discovery, incident classification, synthesis",
        "threat_hunter": "6 SAIA→MCP hunt pipelines, IOC extraction",
        "rca_agent": "Saved search discovery, timeline correlation",
        "blast_radius": "Dynamic blast queries, dependency mapping",
        "remediation": "SAIA advice, runbook retrieval, action planning",
    }
    for agent_name in ["orchestrator", "threat_hunter", "rca_agent", "blast_radius", "remediation"]:
        count = agent_logs.get(agent_name, 0)
        actions_desc = agent_actions.get(agent_name, "")
        sections.append(f"| {agent_name} | {count} | {actions_desc} |")
    sections.append("")

    # ================================================================
    # SECTION 10: Prevention Recommendations
    # ================================================================
    sections.append("---")
    sections.append("## 10. AI-Suggested Prevention Steps")
    sections.append("")
    sections.append("Based on the root cause analysis and attack chain, the following preventive measures are recommended:")
    sections.append("")

    prevention_steps = [
        ("🔐 Enforce MFA for all accounts",
         "Especially service accounts and privileged users. This would have prevented the initial credential compromise. **Priority: IMMEDIATE.**"),
        ("🛡️ Implement credential stuffing protection",
         "Deploy account lockout policies (5 failures / 15 min), CAPTCHA on public login pages, and IP-based rate limiting on authentication endpoints."),
        ("📋 Deploy application whitelisting",
         "Prevent unauthorized tools like PsExec, wget, curl from executing on servers. Use AppLocker or a similar solution."),
        ("🔒 Enhance network segmentation",
         "Restrict lateral movement between workstations and sensitive servers. Implement zero-trust network architecture with micro-segmentation."),
        ("🌐 Deploy DNS filtering",
         "Block known C2 domains and implement DNS sinkholing. Subscribe to threat intelligence feeds for automated blocklist updates."),
        ("⏰ Monitor scheduled task creation",
         "Alert on new scheduled tasks or cron jobs created outside of change management windows. Integrate with Splunk for real-time detection."),
        ("🔑 Implement LAPS / Password Rotation",
         "Use Local Administrator Password Solution to prevent credential reuse across endpoints. Enforce 90-day rotation for service accounts."),
        ("📊 Deploy UEBA",
         "Implement User and Entity Behavior Analytics to detect anomalous authentication patterns before they escalate to full compromise."),
    ]

    for i, (title, description) in enumerate(prevention_steps, 1):
        sections.append(f"{i}. **{title}** — {description}")
    sections.append("")

    # ================================================================
    # FOOTER
    # ================================================================
    sections.append("---")
    sections.append("")
    sections.append(f"*This post-mortem was automatically generated by SentinelOps at {now}. "
                   f"Total Splunk AI calls: {total_saia + total_spl + total_saved + 5}. "
                   f"Report should be reviewed by the incident response team before distribution.*")
    sections.append("")
    sections.append("**Powered by:** Splunk MCP Server v1.1 | Splunk AI Assistant | LangGraph | SentinelOps")

    return "\n".join(sections)
